### ISSUE TITLE
Failed to load application: No Option 'rsa_public_key' in section: 'honeypot'.

### ISSUE THREAD

**Issue by Waseem-farooqui** [desaster/kippo#184]
I was running kippo for couples of months but it stops working whenever I start it, it throws me this error.**Failed to load application: No Option 'rsa_public_key' in section: 'honeypot'** how I can remove.

**Comment by micheloosterhof** [comment]
Do you have the option 'rsa_public_key' in your [honeypot] session in kippo.cfg?

**Comment by Waseem-farooqui** [comment]
No there is no such option is `kippo.cfg` ?

**Comment by micheloosterhof** [comment]
There should be. Check
https://github.com/desaster/kippo/blob/master/kippo.cfg.dist

**Comment by Waseem-farooqui** [comment]
I am using Honeydrive for a long time its working fine on my other system without `rsa_public_key`.
I added this section in configuration now got this error.
`An error has occurred: 'Couldn't listen on 0.0.0.0:22: [Errno 13] Permission denied.'`

**Comment by micheloosterhof** [comment]
Maybe there are some issues with the HoneyDrive configuration.
Your current error appears because you are trying to listen on port 22, and
are probably not root. You probably want a different port to listen on,
2222 is the default. It needs to be higher than 1024 for a non-root user.

**Comment by Waseem-farooqui** [comment]
It was working fine :( some days ago on port 22 and without root user.
When can I do to bind it on port 22?

**Comment by micheloosterhof** [comment]
The first question to ask if it suddenly stopped working is: what changed?
Did you upgrade any components? Any automatic upgrades?

Also, all of these do not seem issues with Kippo but with the HoneyDrive
distribution. Maybe you can ask over there as well:
http://bruteforce.gr/honeydrive

**Comment by Waseem-farooqui** [comment]
Yes It was working fine I restarted the machine with some reasons on starting Kippo service I got this error,
I don't think I upgrade any of its component, no idea regarding automatic upgrade.

At this time I want to know how I can bind kippo on port 22 with non-root user.

**Comment by micheloosterhof** [comment]
http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l

**Comment by abhinavbom** [comment]
I am having similar issue . Running Kippo for the first time.  I do not see any key file being created in /data. I have changed the ssh port to 22. rest everything is default.

twistd (the Twisted daemon) 13.2.0
Copyright (c) 2001-2013 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Generating new RSA keypair...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "kippo.tac", line 34, in <module>
    rsa_pubKeyString, rsa_privKeyString = core.ssh.getRSAKeys()
  File "/opt/kippo/kippo2/kippo/kippo/core/ssh.py", line 271, in getRSAKeys
    with file(public_key, 'w+b') as f:
exceptions.IOError: [Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

Failed to load application: [Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

**Comment by micheloosterhof** [comment]
You have a permissions issue. The user under which you run kip is not allowed to write to the file data/ssh_host_rsa_key.pub.

**Comment by abhinavbom** [comment]
Any suggestion on how I can get rid of it. I know its a kind of low profile question but just wnat to make sure I follow expert advice.

**Comment by micheloosterhof** [comment]
I gave you enough to fix the problem, I suggest you read up on UNIX file permissions.
Do keep in mind you are running a honeypot, you're on purpose inviting people to attack your system. It's good to know a few things about your own systems security as well before you run these.

**Comment by abhinavbom** [comment]
Meanwhile I have it up and running now. Had to permit user access to the kippo folder. Managed to make some normal modifications to cfg as well. 
The system is isolated from any potential environment so I guess I would love people attacking it. 
Let's see how things go.
Thanks for the help.
