### ISSUE TITLE
Failed to download Kippo example logs

### ISSUE THREAD

**Issue by studiawan** [desaster/kippo#199]
I tried to download some logs in Demo section of Readme.md and unfortunately I got this following error:

502 Bad Gateway
nginx/1.6.2

Please check the website http://kippo.rpg.fi for its availability. Thanks!

**Comment by s4wny** [comment]
Duplicate of #193 and #186

**Comment by desaster** [comment]
fixed links with a browser based playlog https://github.com/desaster/playlog-web
