### ISSUE TITLE
Wiki page Running-Kippo is missing a step

### ISSUE THREAD

**Issue by jrmain** [desaster/kippo#212]
Referring to this wiki page:
https://github.com/desaster/kippo/wiki/Running-Kippo

There seems to be a step missing. Specifically, there's nothing about installing Kippo itself. We jump from installing Python modules to configuring Kippo.

**Comment by desaster** [comment]
Kippo is not meant to be installed anywhere in particular. You are supposed to run kippo where you've cloned the repo.

It is possible for a package maintainer to build an "installable" release of kippo, however that's outside this project.

**Comment by jrmain** [comment]
"You are supposed to run kippo where you've cloned the repo."
And yet there's nothing in the instructions that say 'clone the repo' or 'run kippo from where you cloned it'.
