### ISSUE TITLE
.bash_profile

### ISSUE THREAD

**Issue by Eiskaltereistee** [desaster/kippo#221]
Hi,

after the successfully login into the honeypot I want to change the PS1 var for the user.
So I have added three files with the default content (./kippo/honeyfs/root/):
```
-rw-r--r-- 1 kippo kippo   89 Apr 13 10:52 .bash_profile
-rw-r--r-- 1 kippo kippo  693 Apr 13 10:41 .bashrc
-rw-r--r-- 1 kippo kippo  140 Apr 13 10:39 .profile
```

But I am still not able to modify the bash layout with the PS1 var.

What should I do that this works for me?

**Comment by desaster** [comment]
I'm not sure if i understood this correctly, but if you want to edit the prompt that is shown to the attacker, you can find it in honeypot.py -> showPrompt()
