### ISSUE TITLE
kippo.pid permission issue

### ISSUE THREAD

**Issue by BhautikRamani** [desaster/kippo#225]
I got this error when I try to start kippo..

/opt/kippo$ ./start.sh 
twistd (the Twisted daemon) 15.2.0
Copyright (c) 2001-2015 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
An error has occurred: '[Errno 13] Permission denied: '/opt/kippo/kippo.pid''
Please look at log file for more information.

How can I fix it ?

**Comment by desaster** [comment]
duplicate of #224
