### ISSUE TITLE
Kippo not populating to MYSQL 

### ISSUE THREAD

**Issue by bmfmancini** [desaster/kippo#228]
Hello All 

I am seeing an issue where kippo is not populating to a SQL DB 
no errors are populating in kippo log showing sql connection errors 

Here is mysql config from kippo.log

# MySQL logging module
#
# Database structure for this module is supplied in doc/sql/mysql.sql
#
# To enable this module, remove the comments below, including the
# [database_mysql] line.

[database_mysql]
host = 127.0.0.1
database = kippo
username = kippo
password = 
port = 3306

# XMPP Logging
#
# Log to an xmpp server.
# For a detailed explanation on how this works, see: <add url here>
#
# To enable this module, remove the comments below, including the

Here is the SQL tables  which are not populating 

mysql>
mysql>
mysql> select * from sessions;
Empty set (0.00 sec)

mysql> show tables;
+-----------------+
| Tables_in_kippo |
+-----------------+
| auth            |
| clients         |
| downloads       |
| input           |
| sensors         |
| sessions        |
| ttylog          |
+-----------------+
7 rows in set (0.00 sec)

mysql> select * from ttylog
    -> ;
Empty set (0.00 sec)

mysql>
mysql>
mysql> select * from sensors;
Empty set (0.00 sec)

mysql> quit
Bye
kippo@Server:~/kippo$

System setup

admin18@Server:~$
admin18@Server:~$ php -v
PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies
admin18@Server:~$ which php
/usr/bin/php
admin18@Server:~$
admin18@Server:~$ which apache
admin18@Server:~$
admin18@Server:~$ apache2 -v
Server version: Apache/2.4.27 (Ubuntu)
Server built:   2017-09-18T15:05:48
admin18@Server:~$
admin18@Server:~$ uname -a
Linux Server 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
admin18@Server:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
admin18@Server:~$
admin18@Server:~$
admin18@Server:~$ c

**Comment by desaster** [comment]
which version of twisted?

**Comment by bmfmancini** [comment]
You had me at twisted version!

Thanks issue is resolved
