### ISSUE TITLE
Geoip Page Blank

### ISSUE THREAD

**Issue by MelGalea** [desaster/kippo#230]
Hi guys,
Would you possibly know why my Kippo-Graph GEO section is not loading up? Iv'e attached a photo. Maybe this is common and I'm missing something from the configuration? Every other page is working just fine.

Thanks in advance,
Mel.
![geo](https://user-images.githubusercontent.com/38244272/38546779-d8f37274-3cad-11e8-87b7-3bfbb249a0c6.JPG)

**Comment by urhot** [comment]
Unfortunately I don't know about Kippo-Graph. Here's a link to the kippo-graph project on github: https://github.com/ikoniaris/kippo-graph

**Comment by desaster** [comment]
Unfortunately I don't know about Kippo-Graph. Here's a link to the kippo-graph project on github:
https://github.com/ikoniaris/kippo-graph

**Comment by MelGalea** [comment]
Thanks for your response. I'll post this issue onto the Kippo-Graph page instead. Cheers.
