### ISSUE TITLE
shell request failed on channel 0

### ISSUE THREAD

**Issue by ghost** [desaster/kippo#73]
_From [dyn4m1](https://code.google.com/u/108825095450545052585/) on April 03, 2013 14:36:13_

This is what i see, when i try to log into an honeypot...

shell request failed on channel 0

_Original issue: http://code.google.com/p/kippo/issues/detail?id=73_

**Comment by zaer** [comment]
Sorry for open again this post, but the solution is in file "kippo.cfg", in the line 26 or variable log_path, the value is an existing path.

i.e. /home/kippo/log
